# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.get_price_breakdown200_response import GetPriceBreakdown200Response

class TestGetPriceBreakdown200Response(unittest.TestCase):
    """GetPriceBreakdown200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPriceBreakdown200Response:
        """Test GetPriceBreakdown200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPriceBreakdown200Response`
        """
        model = GetPriceBreakdown200Response()
        if include_optional:
            return GetPriceBreakdown200Response(
                debtor_grade = b,
                currency = EUR,
                financed_percentage = 1,
                financed_value = 4712,
                financing_duration = 17,
                fees_amount = 121.17,
                overdue_deposit_days = 60,
                overdue_deposit_percentage = 0.07,
                overdue_deposit_amount = 329.84,
                overdue_deposit_daily_amount = 5.5,
                proceeds_amount = 4260.99
            )
        else:
            return GetPriceBreakdown200Response(
        )
        """

    def testGetPriceBreakdown200Response(self):
        """Test GetPriceBreakdown200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
