# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.get_payables_price_breakdown200_response import GetPayablesPriceBreakdown200Response

class TestGetPayablesPriceBreakdown200Response(unittest.TestCase):
    """GetPayablesPriceBreakdown200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPayablesPriceBreakdown200Response:
        """Test GetPayablesPriceBreakdown200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPayablesPriceBreakdown200Response`
        """
        model = GetPayablesPriceBreakdown200Response()
        if include_optional:
            return GetPayablesPriceBreakdown200Response(
                financing_amount = 500,
                repayment_method = weekly_instalments,
                annual_interest_rate = 0.0975,
                fees_rate = 0.025,
                total_fees_amount = 25.33,
                instalments = None
            )
        else:
            return GetPayablesPriceBreakdown200Response(
        )
        """

    def testGetPayablesPriceBreakdown200Response(self):
        """Test GetPayablesPriceBreakdown200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
