# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.get_client200_response import GetClient200Response

class TestGetClient200Response(unittest.TestCase):
    """GetClient200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClient200Response:
        """Test GetClient200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClient200Response`
        """
        model = GetClient200Response()
        if include_optional:
            return GetClient200Response(
                id = cbbd0a65-a149-436a-99bd-06e819a44da9,
                company_name = Bankable test,
                state = NEW_LEAD,
                product_id = ETR,
                country_code = FI,
                registration_number = 09979111,
                iban = FI1410093000123458,
                bic = BOHIUS77,
                sort_code = 123456,
                account_number = 12345678,
                created_at = 2022-01-05,
                updated_at = 2022-01-06
            )
        else:
            return GetClient200Response(
        )
        """

    def testGetClient200Response(self):
        """Test GetClient200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
