# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bankable.api.payables_finance_api import PayablesFinanceApi


class TestPayablesFinanceApi(unittest.TestCase):
    """PayablesFinanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayablesFinanceApi()

    def tearDown(self) -> None:
        pass

    def test_approve_repayment_plan(self) -> None:
        """Test case for approve_repayment_plan

        Approve Repayment Plan
        """
        pass

    def test_decline_repayment_plan(self) -> None:
        """Test case for decline_repayment_plan

        Decline Repayment Plan
        """
        pass

    def test_find_payables(self) -> None:
        """Test case for find_payables

        List Payables
        """
        pass

    def test_get_payable_details(self) -> None:
        """Test case for get_payable_details

        Get Payable Details
        """
        pass

    def test_get_payables_price_breakdown(self) -> None:
        """Test case for get_payables_price_breakdown

        Get Payables Finance Price Breakdown
        """
        pass

    def test_submit_payables(self) -> None:
        """Test case for submit_payables

        Submit Payables
        """
        pass


if __name__ == '__main__':
    unittest.main()
