# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.find_client200_response import FindClient200Response

class TestFindClient200Response(unittest.TestCase):
    """FindClient200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindClient200Response:
        """Test FindClient200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindClient200Response`
        """
        model = FindClient200Response()
        if include_optional:
            return FindClient200Response(
                results = None,
                pagination = bankable.models.find_client_200_response_pagination.findClient_200_response_pagination(
                    limit = 20, 
                    offset = 10, 
                    total_items = 2033, )
            )
        else:
            return FindClient200Response(
        )
        """

    def testFindClient200Response(self):
        """Test FindClient200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
