# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.submit_payables200_response import SubmitPayables200Response

class TestSubmitPayables200Response(unittest.TestCase):
    """SubmitPayables200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitPayables200Response:
        """Test SubmitPayables200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitPayables200Response`
        """
        model = SubmitPayables200Response()
        if include_optional:
            return SubmitPayables200Response(
                id = 550e8400-e29b-41d4-a716-446655440000,
                created_at = None,
                state = SUBMITTED,
                total_requested_amount = 600,
                currency = EUR,
                invoice_payable_count = 3,
                instalments_count = 3,
                total_repayment_amount = 645.99,
                total_fees_amount = 45.98,
                instalments = None
            )
        else:
            return SubmitPayables200Response(
        )
        """

    def testSubmitPayables200Response(self):
        """Test SubmitPayables200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
