# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.create_client_request import CreateClientRequest

class TestCreateClientRequest(unittest.TestCase):
    """CreateClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateClientRequest:
        """Test CreateClientRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateClientRequest`
        """
        model = CreateClientRequest()
        if include_optional:
            return CreateClientRequest(
                registration_number = 09979111,
                country_code = GB,
                product = credit-line,
                contact = bankable.models.contact.contact(
                    first_name = John, 
                    last_name = Doe, 
                    email = test@domain.com, 
                    phone_country_dial = 34, 
                    phone_number = 632454331, )
            )
        else:
            return CreateClientRequest(
                registration_number = 09979111,
                country_code = GB,
                product = credit-line,
                contact = bankable.models.contact.contact(
                    first_name = John, 
                    last_name = Doe, 
                    email = test@domain.com, 
                    phone_country_dial = 34, 
                    phone_number = 632454331, ),
        )
        """

    def testCreateClientRequest(self):
        """Test CreateClientRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
