# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bankable.models.get_payable_details200_response import GetPayableDetails200Response

class TestGetPayableDetails200Response(unittest.TestCase):
    """GetPayableDetails200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPayableDetails200Response:
        """Test GetPayableDetails200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPayableDetails200Response`
        """
        model = GetPayableDetails200Response()
        if include_optional:
            return GetPayableDetails200Response(
                id = 550e8400-e29b-41d4-a716-446655440000,
                created_at = None,
                updated_at = None,
                state = SUBMITTED,
                reject_reason = LIMIT_EXCEEDED,
                decline_reason = Not happy with the pricing,
                total_requested_amount = 600,
                currency = EUR,
                invoice_payable_count = 3,
                instalments_count = 3,
                repayment_method = weekly_instalments,
                annual_interest_rate = 0.0975,
                fees_rate = 0.025,
                total_repayment_amount = 645.99,
                total_interest_amount = 45.98,
                total_fees_amount = 45.98,
                instalments = None
            )
        else:
            return GetPayableDetails200Response(
        )
        """

    def testGetPayableDetails200Response(self):
        """Test GetPayableDetails200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
