# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bankable.api.credit_api import CreditApi


class TestCreditApi(unittest.TestCase):
    """CreditApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_credit(self) -> None:
        """Test case for cancel_credit

        Cancel Credit
        """
        pass

    def test_create_credit(self) -> None:
        """Test case for create_credit

        Submit Credit
        """
        pass

    def test_find_credits(self) -> None:
        """Test case for find_credits

        List Credits
        """
        pass

    def test_get_credit(self) -> None:
        """Test case for get_credit

        Get Credit Details
        """
        pass

    def test_get_credit_price_breakdown(self) -> None:
        """Test case for get_credit_price_breakdown

        Get Credit Price Breakdown
        """
        pass


if __name__ == '__main__':
    unittest.main()
