# coding: utf-8

"""
    Credit

    # Introduction Description of Bankable Credit RESTful API. Current limitations: - The Credit service does not support [cross origin headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for security reasons. It is not possible to use Swagger UI and make API calls directly from the browser. - Modification API requests (`POST`, `DELETE`) require additional security scopes granted under the service agreement. - Consider the Bankable limitations for API calls that depend on the contract agreement.

    The version of the OpenAPI document: b6bf82e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bankable.api.client_financials_api import ClientFinancialsApi


class TestClientFinancialsApi(unittest.TestCase):
    """ClientFinancialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientFinancialsApi()

    def tearDown(self) -> None:
        pass

    def test_get_financing_indicator(self) -> None:
        """Test case for get_financing_indicator

        Get financing indicator
        """
        pass

    def test_import_financial(self) -> None:
        """Test case for import_financial

        Submit Financial Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
